
[input]
base_directory = "posts"
url_prefix = "https://healeycodes.com/"
frontmatter_handling = "Omit"
files = [{
        path = "a-website-for-100-years.md",
        url = "a-website-for-100-years",
        title = "What If I Want My Website to Last for 100 Years?"
},{
        path = "adding-comments-to-gatsby-with-netlify-and-github.md",
        url = "adding-comments-to-gatsby-with-netlify-and-github",
        title = "Adding Comments to Gatsby with Netlify Serverless Functions + GitHub"
},{
        path = "boids-flocking-simulation.md",
        url = "boids-flocking-simulation",
        title = "Boids in WebAssembly Using Go"
},{
        path = "book-review-the-developers-guide-to-content-creation.md",
        url = "book-review-the-developers-guide-to-content-creation",
        title = "Book Review: The Developer's Guide to Content Creation"
},{
        path = "bot-vs-isp.md",
        url = "bot-vs-isp",
        title = "I Built a Bot to Try and Get Money Back From My Internet Provider"
},{
        path = "build-passing-badge.md",
        url = "build-passing-badge",
        title = "Earn a Build Passing Badge on GitHub! Testing Your Express App with Travis CI (Tutorial)"
},{
        path = "building-my-own-chess-engine.md",
        url = "building-my-own-chess-engine",
        title = "Building My Own Chess Engine"
},{
        path = "cloning-memcached-with-go.md",
        url = "cloning-memcached-with-go",
        title = "Cloning Memcached with Go"
},{
        path = "computer-vision-and-embroidery.md",
        url = "computer-vision-and-embroidery",
        title = "Computer Vision and Embroidery"
},{
        path = "creating-randomness.md",
        url = "creating-randomness",
        title = "Creating Randomness Without Math.random"
},{
        path = "creating-the-golfcart-programming-language.md",
        url = "creating-the-golfcart-programming-language",
        title = "Creating the Golfcart Programming Language"
},{
        path = "day-in-the-life.md",
        url = "day-in-the-life",
        title = "A Day in the Life of a Mediumly Productive Software Engineer"
},{
        path = "dead-link-bot.md",
        url = "dead-link-bot",
        title = "Build a Python Bot to Find Your Website's Dead Links (Tutorial)"
},{
        path = "dev-article-analysis.md",
        url = "dev-article-analysis",
        title = "DEV Article Analysis"
},{
        path = "embed-dev-posts.md",
        url = "embed-dev-posts",
        title = "Embed Your Latest DEV Posts Anywhere (Tutorial)"
},{
        path = "emoji-streamer.md",
        url = "emoji-streamer",
        title = "Real-Time Streaming of Every Emoji Posted as a Comment to Reddit.com"
},{
        path = "flappy-bird.md",
        url = "flappy-bird",
        title = "How Flappy Bird Got Me My Start in Software"
},{
        path = "gatsby-sparks-joy.md",
        url = "gatsby-sparks-joy",
        title = "Gatsby Sparks Joy"
},{
        path = "generating-text-with-markov-chains.md",
        url = "generating-text-with-markov-chains",
        title = "Generating Text With Markov Chains"
},{
        path = "geoguessing-with-deep-learning.md",
        url = "geoguessing-with-deep-learning",
        title = "GeoGuessing with Deep Learning"
},{
        path = "glitch-to-github-via-webhook.md",
        url = "glitch-to-github-via-webhook",
        title = "Continuous Deployment to Glitch via GitHub Webhooks"
},{
        path = "hacking-together-an-e-ink-dashboard.md",
        url = "hacking-together-an-e-ink-dashboard",
        title = "Hacking Together an E-ink Dashboard"
},{
        path = "hardest-javascript-puzzle.md",
        url = "hardest-javascript-puzzle",
        title = "Hardest JavaScript Puzzle I've Ever Solved"
},{
        path = "high-performance-javascript.md",
        url = "high-performance-javascript",
        title = "Solving Puzzles With High-Performance JavaScript"
},{
        path = "how-im-working-remotely.md",
        url = "how-im-working-remotely",
        title = "How I'm Working Remotely"
},{
        path = "interview-question-progress-bar.md",
        url = "interview-question-progress-bar",
        title = "Interview Question: Implement a Progress Bar"
},{
        path = "introduction-to-caching-with-python.md",
        url = "introduction-to-caching-with-python",
        title = "An Introduction to Caching on the Web, With Examples in Python"
},{
        path = "javascript-one-liners.md",
        url = "javascript-one-liners",
        title = "JavaScript One-Liners That Make Me Excited"
},{
        path = "learn-the-storage-api.md",
        url = "learn-the-storage-api",
        title = "Learn the Storage API by Building a Note Taking App (Tutorial)"
},{
        path = "learning-the-ink-programming-language.md",
        url = "learning-the-ink-programming-language",
        title = "Learning the Ink Programming Language"
},{
        path = "leetcode-ep1.md",
        url = "leetcode-ep1",
        title = "Leetcode - Episode 1 - Three Easys"
},{
        path = "leetcode-ep10.md",
        url = "leetcode-ep10",
        title = "Leetcode - Episode 10 - Short Solutions (1 x M, 2 x E)"
},{
        path = "leetcode-ep11.md",
        url = "leetcode-ep11",
        title = "Leetcode - Episode 11 - Faster than 99.17% (1 x M, 2 x E)"
},{
        path = "leetcode-ep12.md",
        url = "leetcode-ep12",
        title = "Leetcode - Episode 12 - Starting Early (3 x E)"
},{
        path = "leetcode-ep13.md",
        url = "leetcode-ep13",
        title = "Leetcode - Episode 13 - Finding My Stride (3 x M)"
},{
        path = "leetcode-ep14.md",
        url = "leetcode-ep14",
        title = "Leetcode - Episode 14 - Short, Easy Solutions (3 x E)"
},{
        path = "leetcode-ep15.md",
        url = "leetcode-ep15",
        title = "Leetcode - Episode 15 - Three Tree Qs (3 x E)"
},{
        path = "leetcode-ep16.md",
        url = "leetcode-ep16",
        title = "Leetcode - Episode 16 - Pretty Efficient (3 x E)"
},{
        path = "leetcode-ep17.md",
        url = "leetcode-ep17",
        title = "Leetcode - Episode 17 - Moving, Shaking, and Folding (3 x E)"
},{
        path = "leetcode-ep2.md",
        url = "leetcode-ep2",
        title = "Leetcode - Episode 2 - Three More Easys"
},{
        path = "leetcode-ep3.md",
        url = "leetcode-ep3",
        title = "Leetcode - Episode 3 - The Streak Continues (3x E)"
},{
        path = "leetcode-ep4.md",
        url = "leetcode-ep4",
        title = "Leetcode - Episode 4 - gnivloS melborP (3x E)"
},{
        path = "leetcode-ep5.md",
        url = "leetcode-ep5",
        title = "Leetcode - Episode 5 - Fastest Solutions Yet (3x E)"
},{
        path = "leetcode-ep6.md",
        url = "leetcode-ep6",
        title = "Leetcode - Episode 6 - Progressively Harder (3x E)"
},{
        path = "leetcode-ep7.md",
        url = "leetcode-ep7",
        title = "Leetcode - Episode 7 - Getting More Pythonic (3x E)"
},{
        path = "leetcode-ep8.md",
        url = "leetcode-ep8",
        title = "Leetcode - Episode 8 - Breaking Out Some Mediums (3x M, 1x E)"
},{
        path = "leetcode-ep9.md",
        url = "leetcode-ep9",
        title = "Leetcode - Episode 9 - Trudging Through (3x E)"
},{
        path = "lets-generate-captchas.md",
        url = "lets-generate-captchas",
        title = "Let's Build a CAPTCHA Generator with Node.js"
},{
        path = "listening-to-satellites-with-my-raspberry-pi.md",
        url = "listening-to-satellites-with-my-raspberry-pi",
        title = "Listening to Satellites with my Raspberry Pi"
},{
        path = "majority-vote-algorithm.md",
        url = "majority-vote-algorithm",
        title = "Fun With Linear Time: My Favorite Algorithm"
},{
        path = "my-experience-with-pair-programming.md",
        url = "my-experience-with-pair-programming",
        title = "My Experience with Pair Programming"
},{
        path = "my-first-golang-program.md",
        url = "my-first-golang-program",
        title = "My First Golang Program"
},{
        path = "order-tracking-micro.md",
        url = "order-tracking-micro",
        title = "Cloning Dominos Order Tracker as a Microservice with Node.js and Firebase!"
},{
        path = "personal-websites-and-internet-writing.md",
        url = "personal-websites-and-internet-writing",
        title = "Personal Websites and Internet Writing"
},{
        path = "polyfilling-fetch.md",
        url = "polyfilling-fetch",
        title = "Polyfilling the Fetch API for Old Browsers and Node.js"
},{
        path = "practical-intro-to-graphs.md",
        url = "practical-intro-to-graphs",
        title = "A Practical Introduction to Graphs (Network Diagrams)"
},{
        path = "privacy-focused-analytics-from-scratch.md",
        url = "privacy-focused-analytics-from-scratch",
        title = "Privacy Focused Analytics From Scratch"
},{
        path = "project-mood.md",
        url = "project-mood",
        title = "Creating Cute GitHub Badges Based Off a Project's Mood (Node.js)"
},{
        path = "raspberry-pi-live-cam.md",
        url = "raspberry-pi-live-cam",
        title = "Coding a Live Cam for the Raspberry Pi in Python (Tutorial)"
},{
        path = "reddit-bot-tutorial.md",
        url = "reddit-bot-tutorial",
        title = "Need a Friend? Write a Reddit Bot with Python to Follow You Around (Tutorial)"
},{
        path = "refactoring-for-performance-and-readability.md",
        url = "refactoring-for-performance-and-readability",
        title = "Refactoring JavaScript for Performance and Readability (with Examples!)"
},{
        path = "saving-data-in-javascript-without-a-database.md",
        url = "saving-data-in-javascript-without-a-database",
        title = "Saving Data in JavaScript Without a Database"
},{
        path = "secret-sudoku.md",
        url = "secret-sudoku",
        title = "I Ported Sudoku to Your URL Bar and It Plays like a Dream"
},{
        path = "talking-between-languages.md",
        url = "talking-between-languages",
        title = "Talking to Python from JavaScript (and Back Again!)"
},{
        path = "the-flow-of-knowledge-in-an-engineering-team-or-why-I-dig-tickets.md",
        url = "the-flow-of-knowledge-in-an-engineering-team-or-why-I-dig-tickets",
        title = "The Flow of Knowledge in a Team (or Why I Dig Tickets)"
},{
        path = "the-weird-rules-i-set-myself.md",
        url = "the-weird-rules-i-set-myself",
        title = "The Weird Rules I Set Myself That Got Me a Job"
},{
        path = "tiny-project-to-completion.md",
        url = "tiny-project-to-completion",
        title = "A Tiny Project, From Inception to Deployment"
},{
        path = "tricking-google-with-apostrophes.md",
        url = "tricking-google-with-apostrophes",
        title = "A Tutorial on Tricking Google: Encoding Messages in Apostrophes"
},{
        path = "twitter-ticker-tape.md",
        url = "twitter-ticker-tape",
        title = "Twitter Ticker Tape with a POS58 Receipt Printer"
},{
        path = "two-things.md",
        url = "two-things",
        title = "Two Things About My First In-house Software Job That I Didn't See Coming"
},{
        path = "webassembly-search-tools-for-static-websites.md",
        url = "webassembly-search-tools-for-static-websites",
        title = "WebAssembly Search Tools for Static Sites"
},{
        path = "websocket-benchmarker.md",
        url = "websocket-benchmarker",
        title = "Benchmarking WebSocket Servers with Python!"
},{
        path = "websockets-javascript-kicking.md",
        url = "websockets-javascript-kicking",
        title = "Kicking Butt and Taking Names With WebSockets (Tutorial)"
},{
        path = "what-the-heck-is-code-golf.md",
        url = "what-the-heck-is-code-golf",
        title = "Answered: What the Heck is Code Golf?"
},{
        path = "what-they-dont-teach-you-at-a-CS-masters.md",
        url = "what-they-dont-teach-you-at-a-CS-masters",
        title = "What They Don't Teach You at a Computer Science Masters"
},{
        path = "writing-an-awesome-github-readme.md",
        url = "writing-an-awesome-github-readme",
        title = "How to Write an Awesome GitHub README"
},{
        path = "writing-software-for-an-among-us-league.md",
        url = "writing-software-for-an-among-us-league",
        title = "Writing Software for an Among Us League"
},{
        path = "your-first-open-source-contribution.md",
        url = "your-first-open-source-contribution",
        title = "Your First Open-Source Pull Request: a Walkthrough"
},]
